"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { adminRequest, jsonRequest } from "@/lib/admin-api";

type Campaign = { id: number; name: string; title: string; placement: string; image_url: string; target_url: string; starts_at: string; ends_at: string; is_active: boolean };

export function AdManager() {
  const [items, setItems] = useState<Campaign[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setItems((await adminRequest<{ items: Campaign[] }>("ads")).items); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar campanhas."); } }, []);
  useEffect(() => { adminRequest<{ items: Campaign[] }>("ads").then((data) => setItems(data.items)).catch((reason) => setError(reason instanceof Error ? reason.message : "Falha ao carregar campanhas.")); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const payload = { name: form.get("name"), title: form.get("title"), placement: form.get("placement"), image_url: form.get("image_url"), target_url: form.get("target_url"), alt_text: form.get("alt_text"), starts_at: new Date(String(form.get("starts_at"))).toISOString(), ends_at: new Date(String(form.get("ends_at"))).toISOString(), is_active: true }; try { await adminRequest("ads", jsonRequest("POST", payload)); event.currentTarget.reset(); setOpen(false); setMessage("Campanha criada."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao criar campanha."); } }
  async function archive(campaign: Campaign) { try { await adminRequest(`ads/${campaign.id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao encerrar campanha."); } }
  return <section className="manager-layout"><div className="manager-toolbar"><div><strong>{items.length}</strong><span>campanhas cadastradas</span></div><button className="button primary" onClick={() => setOpen((value) => !value)}>{open ? "Fechar" : "+ Nova campanha"}</button></div>{open && <form className="admin-form card" onSubmit={create}><div className="form-heading"><h2>Nova campanha</h2><p>Use uma imagem já otimizada no Gestor de Mídia.</p></div><div className="form-grid"><label>Nome interno<input name="name" required minLength={3} /></label><label>Título público<input name="title" required minLength={3} /></label><label>Posição<select name="placement"><option value="HOME_TOPO">Home · topo</option><option value="HOME_CONTEUDO">Home · conteúdo</option><option value="ACADEMIA">Academia</option><option value="MAPA">Mapa</option></select></label><label>Imagem<input name="image_url" required placeholder="/media/arquivo.webp" /></label><label className="wide">Destino HTTPS<input name="target_url" type="url" required pattern="https://.*" /></label><label className="wide">Texto alternativo<input name="alt_text" required minLength={5} maxLength={180} /></label><label>Início<input name="starts_at" type="datetime-local" required /></label><label>Término<input name="ends_at" type="datetime-local" required /></label></div><button className="button primary">Criar campanha</button></form>}{error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}<div className="admin-table-wrap card"><table className="admin-table"><thead><tr><th>Campanha</th><th>Posição</th><th>Período</th><th>Status</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={5}>Nenhuma campanha.</td></tr> : items.map((campaign) => <tr key={campaign.id}><td><strong>{campaign.name}</strong><small>{campaign.title}</small></td><td>{campaign.placement.toLowerCase().replaceAll("_", " ")}</td><td>{new Date(campaign.starts_at).toLocaleDateString("pt-BR")} → {new Date(campaign.ends_at).toLocaleDateString("pt-BR")}</td><td><span className={`status-button ${campaign.is_active ? "published" : "draft"}`}>{campaign.is_active ? "ativa" : "encerrada"}</span></td><td className="table-actions"><button onClick={() => archive(campaign)}>Encerrar</button></td></tr>)}</tbody></table></div></section>;
}
