import type { AcademyPost, AcademyPostSummary, Beach, CommunityThread, FishingPoint, FishingScore } from "./types";

export const demoBeaches: Beach[] = [
  {
    id: 1,
    name: "Praia de Itaúna",
    slug: "praia-de-itauna",
    city: "Saquarema",
    state: "RJ",
    description: "Praia de tombo e mar aberto, com leitura técnica de canais e valas.",
    latitude: -22.9347,
    longitude: -42.4964,
    sea_bearing_deg: 160,
    beach_profile: "TOMBO",
    accessibility_summary: "Acesso urbano; atenção ao mar de tombo.",
  },
  {
    id: 2,
    name: "Praia do Forte",
    slug: "praia-do-forte",
    city: "Cabo Frio",
    state: "RJ",
    description: "Faixa extensa com variação de bancos de areia e canais.",
    latitude: -22.884,
    longitude: -42.0181,
    sea_bearing_deg: 145,
    beach_profile: "INTERMEDIARIA",
    accessibility_summary: "Orla urbanizada e acessível.",
  },
  {
    id: 3,
    name: "Praia Grande",
    slug: "praia-grande-arraial",
    city: "Arraial do Cabo",
    state: "RJ",
    description: "Água fria e clara sob influência da ressurgência.",
    latitude: -22.979,
    longitude: -42.0387,
    sea_bearing_deg: 215,
    beach_profile: "INTERMEDIARIA",
    accessibility_summary: "Calçadão e acessos por escadas.",
  },
];

export const demoPoints: FishingPoint[] = [
  {
    id: 1,
    name: "Canal central",
    slug: "canal-central",
    point_type: "CANAL_RETORNO",
    description: "Saída d'água entre duas coroas, variável com o swell.",
    latitude: -22.9352,
    longitude: -42.4949,
    accessibility: "MODERADA",
    access_notes: "Caminhada curta pela areia.",
    risk_notes: "Não entre no canal; posição muda após ressacas.",
    verified_at: "2026-08-25T12:00:00Z",
  },
  {
    id: 2,
    name: "Vala norte",
    slug: "vala-norte",
    point_type: "BURACO",
    description: "Vala paralela à praia, produtiva na enchente.",
    latitude: -22.9327,
    longitude: -42.4986,
    accessibility: "FACIL",
    access_notes: "Acesso pela avenida principal.",
    risk_notes: null,
    verified_at: "2026-08-24T09:00:00Z",
  },
];

export const demoScore: FishingScore = {
  score: 78,
  label: "muito bom",
  calculated_at: new Date().toISOString(),
  conditions: {
    wind_speed_mps: 4.2,
    wind_direction_deg: 330,
    sea_bearing_deg: 160,
    wind_is_offshore: true,
    tide_trend: "enchendo",
    wave_height_m: 1.1,
    wave_period_s: 10,
    water_temperature_c: 22.4,
    pressure_hpa: 1017,
    moon_phase: "nova",
  },
  breakdown: { vento: 26, mare: 23, ondas: 15, temperatura: 7, pressao: 5, lua: 2 },
  reasons: ["Vento terral moderado", "Maré enchendo", "Swell com período favorável"],
  warnings: ["Dados demonstrativos: conecte as chaves meteorológicas para leitura ao vivo."],
  data_quality: {
    is_sufficient: true,
    confidence_percentage: 92,
    available_components: ["vento", "maré", "ondas", "temperatura", "pressão", "lua"],
    missing_components: [],
  },
  cached: false,
};

export const demoPosts: AcademyPostSummary[] = [
  {
    id: 1,
    title: "Como ler canais e valas antes do primeiro arremesso",
    slug: "como-ler-canais-e-valas",
    excerpt: "Um método visual para localizar água profunda, correntes e zonas de alimentação.",
    content_type: "TUTORIAL",
    featured_image_url: null,
    seo_title: "Leitura de praia para surfcasting",
    seo_description: "Aprenda a identificar canais, valas e coroas de areia.",
    published_at: "2026-08-20T12:00:00Z",
    author: { name: "Equipe Long Cast", username: "equipe" },
  },
  {
    id: 2,
    title: "Conjunto long cast para linhas finas com segurança",
    slug: "conjunto-long-cast-linhas-finas",
    excerpt: "Vara, molinete, linha 0,18 mm e shock leader dimensionados como um único sistema.",
    content_type: "EQUIPAMENTO",
    featured_image_url: null,
    seo_title: "Equipamento long cast de alto rendimento",
    seo_description: "Ficha técnica para um conjunto long cast seguro e equilibrado.",
    published_at: "2026-08-18T12:00:00Z",
    author: { name: "Equipe Long Cast", username: "equipe" },
  },
  {
    id: 3,
    title: "Nó de união para shock leader cônico",
    slug: "no-uniao-shock-leader-conico",
    excerpt: "Passo a passo compacto para uma união resistente e de baixo perfil.",
    content_type: "VIDEO",
    featured_image_url: null,
    seo_title: "Nó para shock leader cônico",
    seo_description: "Monte uma união compacta entre linha principal e arranque.",
    published_at: "2026-08-15T12:00:00Z",
    author: { name: "Equipe Long Cast", username: "equipe" },
  },
];

export const demoPostDetails: Record<string, AcademyPost> = {
  "como-ler-canais-e-valas": {
    ...demoPosts[0],
    content: "## Observe antes de montar\n\nProcure diferenças na cor e no comportamento da espuma. Água mais escura costuma indicar maior profundidade. Uma faixa onde a espuma retorna ao mar pode sinalizar um canal.\n\n### Valide com segurança\n\nUse sucessivos arremessos curtos com chumbo compatível para sentir o relevo. Estruturas mudam após ressacas: trate todo ponto marcado no mapa como referência, nunca como garantia.",
    video_url: null,
    equipment_specification: null,
  },
  "conjunto-long-cast-linhas-finas": {
    ...demoPosts[1],
    content: "## Sistema equilibrado\n\nLinha fina só é segura quando vara, peso de arremesso e shock leader trabalham juntos. Confira desgaste e nós antes de cada sessão.",
    video_url: null,
    equipment_specification: {
      rod_length_m: 4.5,
      rod_construction: "Tubular",
      reel_size: 9000,
      main_line_material: "Monofilamento",
      main_line_diameter_mm: 0.18,
      shock_leader_type: "Cônico 0,20–0,57 mm",
      casting_weight_min_g: 100,
      casting_weight_max_g: 150,
      extra_specs: null,
    },
  },
  "no-uniao-shock-leader-conico": {
    ...demoPosts[2],
    content: "## Antes de apertar\n\nUmedeça o nó, ajuste as voltas sem cruzá-las e faça um teste progressivo de tração. Descarte o trecho se houver abrasão.",
    video_url: null,
    equipment_specification: null,
  },
};

export const demoThreads: CommunityThread[] = [
  {
    id: 1,
    title: "Leitura da enchente em Itaúna nesta manhã",
    content: "A vala norte ficou mais definida na primeira hora da enchente. Vento terral leve e água clara; confirme a posição porque a última ressaca deslocou a coroa.",
    category: "RELATO",
    media_url: null,
    author: { name: "Marcos Silva", username: "marcos.s", avatar_url: null },
    beach: { name: "Praia de Itaúna", slug: "praia-de-itauna" },
    comment_count: 2,
    reaction_count: 7,
    created_at: "2026-08-29T10:00:00Z",
    updated_at: "2026-08-29T11:30:00Z",
    comments: [
      { id: 1, content: "Boa leitura. O canal estava dois postes mais ao norte ontem.", author: { name: "Ana Costa", username: "ana.cast", avatar_url: null }, created_at: "2026-08-29T10:30:00Z" },
      { id: 2, content: "Vale reforçar: corrente forte na vazante.", author: { name: "Paulo Reis", username: "paulo.r", avatar_url: null }, created_at: "2026-08-29T11:30:00Z" },
    ],
  },
  {
    id: 2,
    title: "Dúvida sobre shock leader para chumbo de 130 g",
    content: "Estou usando mono 0,18 mm e vara tubular de 4,50 m. Qual faixa de arranque vocês recomendam para arremesso apoiado?",
    category: "DUVIDA",
    media_url: null,
    author: { name: "Lucas Moreira", username: "lucas.long", avatar_url: null },
    beach: null,
    comment_count: 0,
    reaction_count: 3,
    created_at: "2026-08-28T15:00:00Z",
    updated_at: "2026-08-28T15:00:00Z",
    comments: [],
  },
];
